
version: '3.9'

services:
  db:
    image: mysql    
    restart: always   
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db      
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password      
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=''

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db
volumes:
  my-db: