# Generated by Django 4.2.6 on 2023-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
